### ISSUE TITLE
Issue with Custom event property for Xamarin iOS

### ISSUE THREAD

**Issue by Michael12jan** [urbanairship/urbanairship-xamarin#106]
# Preliminary Info
I'm implementing Urban Airship into my Xamarin Native app and currently stuck at implementing Custom event property.Here is how I implement the Custom event:

>     UACustomEvent customevent = new UACustomEvent ();
>     customevent.EventName = "Startup";
>     customevent.EventValue = new NSDecimalNumber ("1.0");
>     customevent.SetStringProperty (App.Instance.Settings.AppVersion, "AppVersion");
>     customevent.SetStringProperty ("Debug", "RunMode");
>     customevent.Track ();

Any help will be appreciated, Thanks!
ps: I have registered the event property in the dashboard.

### What Urban Airship dependencies are you using?
Xamarin iOS

### What are the versions of any relevant development tools you are using?
Visual Studio 2018 for Mac

# Report

### What unexpected behavior are you seeing?
 The property does not get registered in the server, the event value and event name does get registered tough. 

### What is the expected behavior?
The property is registered in the server and the associated push event is called.

### What are the steps to reproduce the unexpected behavior?
See code snippet.

### Do you have logging for the issue?
No error.

**Comment by marc-scig** [comment]
Hi @Michael12jan,

I think this is just a problem of not using the right constructor. UACustomEvent on iOS uses static factory methods, such as `eventWithName:value:`. On Xamarin the equivalent in our bindings would be `UACustomEvent.Event(string, NSNumber)`. By using the base constructor, what's probably happening is your code binds to the default inherited `init` method for UACustomEvent, which doesn't initialize the dictionary the properties are stored in.

See the [AirshipKit docs](https://docs.urbanairship.com/reference/libraries/ios/latest/) for more info, and if you're curious how the bindings are set up, you can find those [here](https://github.com/urbanairship/urbanairship-xamarin/blob/master/src/AirshipBindings.iOS/ApiDefinition.cs#L1415)
