### ISSUE TITLE
Could not install package 'urbanairship.ios.locationkit 11.0.0'

### ISSUE THREAD

**Issue by SkylinerX** [urbanairship/urbanairship-xamarin#116]
# Preliminary Info

### What Airship dependencies are you using?
urbanairship.ios (11.0.0)
urbanairship.ios.appextensions (11.0.0)

### What are the versions of any relevant development tools you are using?

I'm currently using:
VS for Mac 8.1.4
Mono 5.18.1.28
Xamarin.iOS 12.10.0.157

# Report

### What unexpected behavior are you seeing?
When trying to install the new Airship Location Kit NuGet i get the following error:

Could not install package 'urbanairship.ios.locationkit 11.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### What is the expected behavior?
The package should install like the "urbanairship.ios (11.0.0)" or "urbanairship.ios.appextensions (11.0.0)" package which i'm currently using without any issues.

### What are the steps to reproduce the unexpected behavior?
Create a Xamarin iOS Project and install the location kit NuGet package.

### Do you have logging for the issue?
https://gist.github.com/SkylinerX/4d02296221bb4ad333cb6df26638dc05

**Comment by BrianBatchelder** [comment]
@SkylinerX : Thanks for the report. We will look into it today.

**Comment by BrianBatchelder** [comment]
@SkylinerX : Version 11.1.0 has just been released. It should address your issue. Please try it and let us know.

**Comment by SkylinerX** [comment]
@BrianBatchelder : Thanks for the quick response. It works now.
