### ISSUE TITLE
Sample App doesn't work

### ISSUE THREAD

**Issue by robatkansys** [urbanairship/urbanairship-xamarin#162]
The sample apps(urbanairship-xamarin/SampleApp/) don't appear to have all the correct references and do not work.  Making them completely worthless as examples.

**Comment by crow** [comment]
@robatkansys We recently replaced the native samples with the forms sample you mentioned - so it's possible a regression was recently introduced. We'll look into it right away. Thanks for reporting.

**Comment by robatkansys** [comment]
Is there a urbanairship.netstandard Version=13.1.0 ?  https://www.nuget.org/packages/urbanairship.netstandard/ only shows 13.0.0

**Comment by crow** [comment]
@robatkansys 13.1.0 hasn't been released yet - it will be released relatively soon.

**Comment by marc-scig** [comment]
@robatkansys 13.1.0 is released. Sorry for the confusion – we migrated recently to use nupkg for the sample app instead of local references but release got held up and part of the change slipped into our main branch. If anything else looks askew just let us know and we'll iron it out.

**Comment by robatkansys** [comment]
When will the nuget package be updated to 13.1.0?

**Comment by rlepinski** [comment]
@robatkansys The packages should be available now
