### ISSUE TITLE
New releases for urbanairship-xamarin

### ISSUE THREAD

**Issue by mkpoul** [urbanairship/urbanairship-xamarin#184]
Nothing have published for 4 months. In the same time iOS/Android versions continue releasing regularly. 
Is there any chance to see something in foreseeable future?

Thanks.

**Comment by rlepinski** [comment]
Its being worked on now, hopefully we can resolve some of our build issues to make updates quicker in the future.

**Comment by mkpoul** [comment]
Thank you for your quick response.

Regards,
Mykhailo

чт, 30 вер. 2021 о 22:55 Ryan Lepinski ***@***.***> пише:

**Comment by rlepinski** [comment]
We are currently up to date on releases!
