### ISSUE TITLE
Action Link is no longer received

### ISSUE THREAD

**Issue by amilici** [urbanairship/urbanairship-xamarin#189]
# Preliminary Info

### What Airship dependencies are you using?
urbanairship.ios.basement
urbanairship.ios.core
urbanairship.ioslocation
urbanairship.ios.messagecenter

16.1.0

Xamarin.iOS 15.2.0.17
Xamarin.Forms 5.0.0.2244

# Report

### What unexpected behavior are you seeing?
The Action Link in the Rich Page content of a Message Center message  is no longer being received by the app on iOS when I tap on the image in the message. The deep link is an Action Link associated with the Rich Page image in the composer. In version 12 of Urban Airship this worked, an we did not use an UADeepLinkDelegate, but registered the url scheme with iOS and got the link in the OpenUrl method of the AppDelegate. After updating to version 13 of Urban Airship this stopped working. Setting a UADeepLinkDelegate to Airship.Shared.DeepLinkDelegate is not working either, ReceivedDeepLink is never being called.

I am using a custom web view to display Message Center messages. As part of the upgrade I had to convert to using a NativeBridge to get the message Rich Page content to display at all.

### What is the expected behavior?
The app should receive the deep link.

### What are the steps to reproduce the unexpected behavior?

1. Make a Message Center message in the Composer where the Rich Page image has a deep link url Action Link.
2. Send it to the device.
3. In the app go to the message center and tap the message to display the Custom Web View. 
4. Tap the image in the Rich Page content of the image.

The deep link used to be received in the OpenUrl method of the AppDelegate.

here is the code for the custom Web View renderer with the native bridge:

```
  public class UrbanAirshipWebViewRenderer : WkWebViewRenderer
    {
        private readonly UANativeBridge _nativeBridge = new NativeBridge();
        private readonly UrbanAirshipWebViewDelegate _navDelegate = new UrbanAirshipWebViewDelegate();

        protected override void OnElementChanged (VisualElementChangedEventArgs e)
        {
            base.OnElementChanged (e);
            if (e.OldElement == null)
            {
                NavigationDelegate = _nativeBridge;
                _nativeBridge.ForwardNavigationDelegate = _navDelegate;
            }
        }

        private class UrbanAirshipWebViewDelegate : UANavigationDelegate
        {
            private bool isLoading;

            [Export("webView:didStartProvisionalNavigation:")]
            public void DidStartProvisionalNavigation(WKWebView webView, WKNavigation navigation)
            {
                if (!isLoading)
                {
                    isLoading = true;

                    var userData = UAMessageCenter.Shared.User.GetUserDataSync();

                    string auth = string.Format("{0}:{1}", userData.Username, userData.Password);
                    string authEncoded = Convert.ToBase64String(Encoding.UTF8.GetBytes(auth));

                    string header = string.Format("Basic {0}", authEncoded);

                    var newRequest = new NSMutableUrlRequest(webView.Url);
                    newRequest["Authorization"] = new NSString(header);

                    webView.LoadRequest(newRequest);
                }
            }
        }

        private class NativeBridge : UANativeBridge, IWKNavigationDelegate
        {

        }
    }
```

**Comment by rlepinski** [comment]
Could you provide the html that is supposed to run the deep link action? You should be able to fetch by downloading them message body directly or you can use safari debugger if you are running the app in a simulator. Safari -> Developer

Could you also provide logs by any chance? I am not sure why this is not working but Ill try to debug it tomorrow to see if we can get this fixed with this release https://github.com/urbanairship/urbanairship-xamarin/pull/186

**Comment by amilici** [comment]
Attached is the html for a Rich Page and log output when the message center and the message page load:

[rich_page.txt](https://github.com/urbanairship/urbanairship-xamarin/files/7695101/rich_page.txt)
[log.log](https://github.com/urbanairship/urbanairship-xamarin/files/7695107/log.log)

Note there is no output to the log when tapping on the image in the web view

**Comment by rlepinski** [comment]
Ok, so it looks like its trying to use the open external url action and not the deep link action. Do you have the allow list setup for this? If not that would prevent it from loading but I would expect to see this log - https://github.com/urbanairship/ios-library/blob/main/Airship/AirshipCore/Source/OpenExternalURLAction.swift#L38

I am trying to get my environment up and going on my machine to test your code. I was able to verify the url was attempted to load on a native app, so its either an issue with your config, your custom view, or the bindings.

**Comment by amilici** [comment]
It was the allow list. 

I've got it working now, thanks for your help. I think you cal close the issue.
