### ISSUE TITLE
.NET 6/7 Support for iOS/Android

### ISSUE THREAD

**Issue by APIWT** [urbanairship/urbanairship-xamarin#208]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
UrbanAirship Messaging

### What are the versions of any relevant development tools you are using?
.NET 7 (iOS and Android)

# Report

### What unexpected behavior are you seeing?
The UrbanAirship nuget packages do not target .NET 6 or .NET 7, making them unusable. They only target Xamarin iOS 1.0

### What is the expected behavior?
A version of the package targeting .NET 6/7 is available, allowing this to be used in modern Xamarin (aka .NET) applications.

### What are the steps to reproduce the unexpected behavior?
Create a .NET MAUI application (or a vanilla .NET for iOS application) and attempt to add the Nuget package.

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
This is in progress, hope to have something in a few weeks.

**Comment by AnthonyIacono** [comment]
> This is in progress, hope to have something in a few weeks.  

Thanks for the update. Is there any way to build it locally in the mean time? I think there is some xamifier package or something that is private so I am unable to when I try following the build instructions in the README.

**Comment by rlepinski** [comment]
It looks like this is the branch - https://github.com/urbanairship/urbanairship-xamarin/tree/MOBILE-3302-net6-maui

But I know there has been more work on it since last month, so I need to check in with the engineer that is working on it. They are currently on vacation, but I will try to connect with them to get the latest work pushed.

**Comment by AnthonyIacono** [comment]
> It looks like this is the branch - https://github.com/urbanairship/urbanairship-xamarin/tree/MOBILE-3302-net6-maui
> 
> 
> 
> But I know there has been more work on it since last month, so I need to check in with the engineer that is working on it. They are currently on vacation, but I will try to connect with them to get the latest work pushed. 

Thanks Ryan. Any idea about the xamafier package thing?

**Comment by rlepinski** [comment]
I dont think so, do you have a link on docs on it? Maybe they made it easier for us?

**Comment by AnthonyIacono** [comment]
> I dont think so, do you have a link on docs on it? Maybe they made it easier for us? 

The repository referred to in this requirements file: https://github.com/urbanairship/urbanairship-xamarin/blob/main/requirements.txt

**Comment by rlepinski** [comment]
Oh that, its no longer used. The reference should be removed.

**Comment by wtaconnerzeuli** [comment]
Oh nice! Excited for this.

**Comment by raver99** [comment]
Any update on this?
We are reimplementing an App that already uses Airship and we are evaluating the possibility to reimplement the App in .NET MAUI. 
An update with a roadmap on this would help us a lot in the decision making progress. Thanks

**Comment by rlepinski** [comment]
Released in [17.0.0](https://github.com/urbanairship/urbanairship-xamarin/releases/tag/17.0.0)
